### ISSUE TITLE
Peer-to-peer Code review

### ISSUE THREAD

**Issue by AkshithaReddy1899** [mugishasam123/awesomebooks#4]
Great work so far 💯 🥇 

few minor issues to make your project perfect.

- [ ] The list objects is placed on top of the footer
![Opera Snapshot_2022-01-06_130448_mugishasam123 github io](https://user-images.githubusercontent.com/70577783/148346626-e3fd0b53-110d-422f-b788-a9a2b36ed7f5.png)

- [ ] The remove button does remove objects from the local storage but it doesn't update the list on the page

**Comment by mugishasam123** [comment]
I solved the issues guys thanks for informing
